using System;
int sno, sclass, m1, m2, m3, m4, m5, m6, tot;
string sname, ssec;
float avg;
System.Console.Clear();
System.Console.Write("Enter student number:");
sno = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter student Name:");
sname = Console.ReadLine();
System.Console.Write("Enter student class:");
sclass = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter student section:");
ssec = Console.ReadLine();
System.Console.Write("Enter 1 marks:");
m1 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter 2 marks:");
m2 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter 3 marks:");
m3 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter 4 marks:");
m4 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter 5 marks:");
m5 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter 6 marks:");
m6 = Convert.ToInt32(Console.ReadLine());
tot = m1 + m2 + m3 + m4 + m5 + m6;
avg = tot / 6;
System.Console.Clear();
System.Console.WriteLine("---------------------------------");
System.Console.WriteLine("student number:" + sno);
System.Console.WriteLine("student name:" + sname);
System.Console.WriteLine("student class:" + sclass);
System.Console.WriteLine("student section:" + ssec);
System.Console.WriteLine("---------------------------------");
System.Console.WriteLine("student 1 mark:" + m1);
System.Console.WriteLine("student 2 mark:" + m2);
System.Console.WriteLine("student 3 mark:" + m3);
System.Console.WriteLine("student 4 mark:" + m4);
System.Console.WriteLine("student 5 mark:" + m5);
System.Console.WriteLine("student 6 mark:" + m6);
System.Console.WriteLine("---------------------------------");
System.Console.WriteLine("Total marks:" + tot);
System.Console.WriteLine("Average marks:" + avg);
System.Console.WriteLine("---------------------------------");